=== jlopez21178-tech/Llenguatje-de-marques/Tema 4/practica/practica4_Jordi_Lopez.dtd
<!ELEMENT factura (capçalera, linia+, total)>

<!ELEMENT capçalera (data, info+)>
<!ATTLIST capçalera id NMTOKEN #REQUIRED>
<!ELEMENT data EMPTY>
<!ATTLIST data
  dia CDATA #REQUIRED
  mes CDATA #REQUIRED
  any CDATA #REQUIRED>
<!ELEMENT info EMPTY>
<!ATTLIST info
  tipus (client | proveidor) #REQUIRED
  nom_fiscal CDATA #REQUIRED
  nom_comercial CDATA #IMPLIED
  nif CDATA #REQUIRED>

<!ELEMENT linia (article)>
<!ATTLIST linia
  id NMTOKEN #REQUIRED
  article_ref IDREF #REQUIRED>
<!ELEMENT article (descripcio, preu, preu_iva)>
<!ATTLIST article
  id ID #REQUIRED
  unitats CDATA #REQUIRED>
<!ELEMENT descripcio (#PCDATA)>
<!ELEMENT preu (#PCDATA)>
<!ELEMENT preu_iva (#PCDATA)>
<!ATTLIST preu_iva tipus (4 | 10 | 21) #REQUIRED>

<!ELEMENT total (subtotal+, amb_iva, sense_iva)>
<!ELEMENT subtotal (#PCDATA)>
<!ATTLIST subtotal article_ref IDREF #REQUIRED>
<!ELEMENT amb_iva (#PCDATA)>
<!ELEMENT sense_iva (#PCDATA)>

=== jlopez21178-tech/Llenguatje-de-marques/Tema 4/practica/practica4_Jordi_Lopez.xml
<?xml version="1.0" encoding="UTF-8"?>

<!DOCTYPE factura SYSTEM "practica4_Jordi_Lopez.dtd">

<factura>
  <capçalera id="abc2">
    <data dia="21" mes="3" any="25"></data>
    <info tipus="client" nom_fiscal="Alfonso"  nif="41611193D"></info>
    <info tipus="proveidor" nom_fiscal="Roberto" nom_comercial="Intel"  nif="4328947D"></info>
  </capçalera>

  <linia id="aksdj" article_ref="askld">
    <article id="askld" unitats="20">
      <descripcio>producte molt bo</descripcio>
      <preu>30</preu>
      <preu_iva tipus="4">34</preu_iva>
    </article>
  </linia>

  <total>
    <subtotal article_ref="askld">320</subtotal>
    <amb_iva>340</amb_iva>
    <sense_iva>320</sense_iva>
  </total>

</factura>
