<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<!DOCTYPE operaciones [
  <!ELEMENT operaciones ((venta*, compra*)+)>

  <!ELEMENT venta (titulo+,cantidad,lliurat?,importe)>
  <!ELEMENT titulo (#PCDATA)>
  <!ELEMENT cantidad (#PCDATA)>
  <!ELEMENT lliurat (#PCDATA)>
  <!ELEMENT importe (#PCDATA)>
  <!ATTLIST importe moneda CDATA #REQUIRED>

  <!ELEMENT compra (titulo+, proveedor, data)>
  <!ELEMENT proveedor (#PCDATA)>
  <!ELEMENT data (dia, mes, año)>
  <!ELEMENT dia (#PCDATA)>
  <!ELEMENT mes (#PCDATA)>
  <!ELEMENT año (#PCDATA)>
]>

<operaciones>

  <venta>
    <titulo>El Cid</titulo>
    <titulo>Lazarillo de Tormes</titulo>

    <cantidad>60</cantidad>
    <lliurat></lliurat>
    <importe moneda="euros">150</importe>
  </venta>

  
  <compra>
    <titulo>El Quijote</titulo>
    <proveedor>Molinete</proveedor>
    <data>
      <dia>01</dia>
      <mes>01</mes>
      <año>2026</año>
    </data>
  </compra>
  
  <venta>
    <titulo>El Cid</titulo>
    <cantidad>30</cantidad>
    <importe moneda="euros">200</importe>
  </venta>

</operaciones>