=== jlopez21178-tech/Llenguatje-de-marques/Tema 4/Exercicis/pack-ex-2/fitxer.dtd
<!ELEMENT operaciones ((venta*, compra*)+)>

<!ELEMENT venta (titulo+,cantidad,lliurat?,importe)>
<!ELEMENT titulo (#PCDATA)>
<!ELEMENT cantidad (#PCDATA)>
<!ELEMENT lliurat (#PCDATA)>
<!ELEMENT importe (#PCDATA)>
<!ATTLIST importe moneda CDATA #REQUIRED>

<!ELEMENT compra (titulo+, proveedor, data)>
<!ELEMENT proveedor (#PCDATA)>
<!ELEMENT data (dia, mes, año)>
<!ELEMENT dia (#PCDATA)>
<!ELEMENT mes (#PCDATA)>
<!ELEMENT año (#PCDATA)>

=== jlopez21178-tech/Llenguatje-de-marques/Tema 4/Exercicis/pack-ex-2/ex1.1.xml
<?xml version="1.0" encoding="UTF-8"?>


<!DOCTYPE operaciones SYSTEM "fitxer.dtd">

<operaciones>
  <compra>
    <titulo></titulo>
    <proveedor></proveedor>
    <data>
      <dia></dia>
      <mes></mes>
      <año></año>
    </data>
  </compra>
</operaciones>
