=== jlopez21178-tech/Llenguatje-de-marques/Tema 4/Exercicis/pack-ex-3/ex1.dtd
<!ELEMENT entrega (lot+)>

<!ELEMENT lot (palet+)>
<!ELEMENT palet (num_caixes, contingut, pes, manipulacio)>

<!ELEMENT num_caixes (#PCDATA)>
<!ELEMENT pes (#PCDATA)>
<!ELEMENT manipulacio (#PCDATA)>

<!ELEMENT contingut (nom, procedencia*, num_serie, pes_individual, unitat_pes?)>
<!ELEMENT nom (#PCDATA)>
<!ELEMENT procedencia (#PCDATA)>
<!ELEMENT num_serie (#PCDATA)>
<!ELEMENT pes_individual (#PCDATA)>
<!ELEMENT unitat_pes (#PCDATA)>

=== jlopez21178-tech/Llenguatje-de-marques/Tema 4/Exercicis/pack-ex-3/ex1.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE entrega SYSTEM "ex1.dtd">

<entrega>

  <lot>
    <palet>
      <num_caixes>29</num_caixes>
      <contingut>
        <nom>GPU</nom>
        <procedencia>CHINA</procedencia>
        <num_serie>12389js0912</num_serie>
        <pes_individual>2000</pes_individual>
        <unitat_pes>grams</unitat_pes>
      </contingut>
      <pes>30000</pes>
      <manipulacio>Fragil, tenir compte</manipulacio>
    </palet>
  </lot>

  <lot>
    <palet>
      <num_caixes>201</num_caixes>
      <contingut>
        <nom>CPU</nom>
        <procedencia>CHINA</procedencia>
        <procedencia>ANGLATERA</procedencia>
        <procedencia>USA</procedencia>
        <procedencia>ALEMANYA</procedencia>
        <num_serie>1239840932850928</num_serie>
        <pes_individual>230</pes_individual>
      </contingut>
      <pes>43000</pes>
      <manipulacio>Tenir compte</manipulacio>
    </palet>
  </lot>

</entrega>
