=== jlopez21178-tech/Llenguatje-de-marques/Tema 4/Exercicis/pack-ex-3/ex2.dtd
<!ELEMENT llistacursos (curs+)>
<!ELEMENT curs (alumne+)>
<!ELEMENT alumne (dni, nom, cognom, segon_cognom?, assignatures)>
<!ELEMENT dni (#PCDATA)>
<!ELEMENT nom (#PCDATA)>
<!ELEMENT cognom (#PCDATA)>
<!ELEMENT segon_cognom (#PCDATA)>
<!ELEMENT assignatures (assignatura+)>
<!ELEMENT assignatura (nom, professor)>
<!ATTLIST assignatura codi ID #REQUIRED>
<!ELEMENT professor (nom, cognom, segon_cognom?)>
<!ATTLIST professor NRP ID #REQUIRED>

=== jlopez21178-tech/Llenguatje-de-marques/Tema 4/Exercicis/pack-ex-3/ex2.xml
<?xml version="1.0" encoding="UTF-8"?>

<!DOCTYPE llistacursos SYSTEM "ex2.dtd">

<llistacursos>
  <curs>
    <alumne>
      <dni></dni>
      <nom></nom>
      <cognom></cognom>
      <segon_cognom></segon_cognom>
      <assignatures>
        <assignatura codi="EN1">
          <nom></nom>
          <professor NRP="MQ32">
            <nom></nom>
            <cognom></cognom>
            <segon_cognom></segon_cognom>
          </professor>
        </assignatura>
      </assignatures>
    </alumne>
  </curs>
</llistacursos>
