=== jlopez21178-tech/Llenguatje-de-marques/Tema 4/Exercicis/pack-ex-3/ex4.dtd
<!ELEMENT llistat (futur+, divisa+, bons+, lletres+)>

<!ELEMENT origen EMPTY>
<!ATTLIST origen capital (Madrid | NovaYork | Frankfurt | Toquio) #REQUIRED>

<!ELEMENT futur (origen, producte, mercat?)>
<!ATTLIST futur preu CDATA #REQUIRED>
<!ELEMENT producte (#PCDATA)>
<!ELEMENT mercat EMPTY>
<!ATTLIST mercat pais (Espanya | Alemanya | USA | Japo) #REQUIRED>


<!ELEMENT divisa (origen, nom, canvi+)>
<!ATTLIST divisa preu CDATA #REQUIRED>
<!ATTLIST divisa estable (0 | 1) #IMPLIED>
<!ELEMENT nom (#PCDATA)>
<!ELEMENT canvi (#PCDATA)>
<!ATTLIST canvi moneda CDATA #REQUIRED>

<!ELEMENT bons (origen, pais_de_procedencia, valors)>
<!ATTLIST bons preu CDATA #REQUIRED>
<!ATTLIST bons estable (0 | 1) #IMPLIED>
<!ELEMENT pais_de_procedencia (#PCDATA)>
<!ELEMENT valors (desitjat, minim, maxim)>
<!ELEMENT desitjat (#PCDATA)>
<!ELEMENT minim (#PCDATA)>
<!ELEMENT maxim (#PCDATA)>

<!ELEMENT lletres (origen, interes)>
<!ATTLIST lletres preu CDATA #REQUIRED>
<!ELEMENT interes (#PCDATA)>
<!ATTLIST interes emissor (Espanya | Alemanya | USA | Japo) #REQUIRED>

=== jlopez21178-tech/Llenguatje-de-marques/Tema 4/Exercicis/pack-ex-3/ex4.1.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE llistat SYSTEM "ex4.dtd">


<llistat>
  <futur preu="30">
    <origen capital="Madrid"></origen>
    <producte>Almohada</producte>
    <mercat pais="Espanya"></mercat>
  </futur>
  <futur preu="200">
    <origen capital="Toquio"></origen>
    <producte>adsj</producte>
    <mercat pais="Espanya"></mercat>
  </futur>
  <futur preu="10000">
    <origen capital="Madrid"></origen>
    <producte>Oro</producte>
    <mercat pais="Espanya"></mercat>
  </futur>

  <divisa preu="10€" estable="1">
    <origen capital="NovaYork"></origen>
    <nom>Euro</nom>
    <canvi moneda="Libra">13</canvi>
    <canvi moneda="Yen">1000</canvi>
    <canvi moneda="Dolar">11</canvi>
  </divisa>

  <bons preu="1" >
    <origen capital="Frankfurt"></origen>
    <pais_de_procedencia></pais_de_procedencia>
    <valors>
      <desitjat></desitjat>
      <minim></minim>
      <maxim></maxim>
    </valors>
  </bons>

  <bons preu="" estable="0">
    <origen capital="Frankfurt"></origen>
    <pais_de_procedencia>Mexico</pais_de_procedencia>
    <valors>
      <desitjat>1000</desitjat>
      <minim>200</minim>
      <maxim>3000</maxim>
    </valors>
  </bons>

  <lletres preu="">
    <origen capital="Toquio"></origen>
    <interes emissor="Espanya"></interes>

  </lletres>

</llistat>

=== jlopez21178-tech/Llenguatje-de-marques/Tema 4/Exercicis/pack-ex-3/ex4.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE llistat SYSTEM "ex4.dtd">


<llistat>
  <futur preu="">
    <origen capital="Madrid"></origen>
    <producte></producte>
    <mercat pais="Espanya"></mercat>
  </futur>

  <divisa preu="10€" estable="1">
    <origen capital="NovaYork"></origen>
    <nom>Euro</nom>
    <canvi moneda="Libra">13</canvi>
    <canvi moneda="Yen">1000</canvi>
    <canvi moneda="Dolar">11</canvi>
  </divisa>

  <bons preu="" estable="1">
    <origen capital="Frankfurt"></origen>
    <pais_de_procedencia></pais_de_procedencia>
    <valors>
      <desitjat></desitjat>
      <minim></minim>
      <maxim></maxim>
    </valors>
  </bons>

  <lletres preu="">
    <origen capital="Toquio"></origen>
    <interes emissor="Espanya"></interes>

  </lletres>

</llistat>
