=== jlopez21178-tech/Llenguatje-de-marques/Tema 4/Exercicis/pack-ex-6/pack6.xsd
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:element name="concesionario">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="modelo" maxOccurs="unbounded">
          <xs:complexType mixed="true">
            <xs:sequence minOccurs="0">
              <xs:element name="motor" type="typeMotor" />
              <xs:element name="potencia" type="xs:string" />
              <xs:element name="consumo_medio">
                <xs:complexType>
                  <xs:simpleContent>
                    <xs:extension base="xs:string">
                      <xs:attribute name="velocidad_km" type="xs:positiveInteger" />
                    </xs:extension>
                  </xs:simpleContent>
                </xs:complexType>
              </xs:element>
            </xs:sequence>
            <xs:attribute name="id" type="xs:ID" />
            <xs:attribute name="modelos_relacionados" type="xs:IDREFS" use="optional" />
          </xs:complexType>
        </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>

  <!-- <xs:complexType name="typeMotor" mixed="true">
    <xs:attribute name="modelos_relacionado" type="xs:IDREFS" use="optional" />
  </xs:complexType> -->

  <xs:complexType name="typeMotor">
    <xs:simpleContent>
      <xs:extension base="xs:string">
        <xs:attribute name="modelos_relacionados" />
      </xs:extension>
    </xs:simpleContent>
  </xs:complexType>
</xs:schema>

=== jlopez21178-tech/Llenguatje-de-marques/Tema 4/Exercicis/pack-ex-6/prova.xml
<?xml version="1.0" encoding="UTF-8"?>

<concesionario
  xmlns:xs="http://www.w3.org/2001/XMLSchema-instance"
  xs:noNamespaceSchemaLocation="pack6.xsd"
>
  <modelo id="Modelo556">No disponible</modelo>

  <modelo id="Modelo555" modelos_relacionados="Modelo444 Modelo556">Este modelo tiene un 
    <motor modelos_relacionados="Modelo556">1.998cc 16v. de cuatro cilindros</motor> 
    que desarrolla una potencia de <potencia>128</potencia> CV. Dispone de cambio manual ... el consumo medio de este
    monovolumen es <consumo_medio velocidad_km="100">11</consumo_medio> a los 100 km. El precio base es de 2.225.000.</modelo>

  <modelo id="Modelo557">No disponible</modelo>

  <modelo id="Modelo154">No disponible</modelo>

  <modelo id="Modelo444" modelos_relacionados="Modelo555 Modelo154">Este modelo tiene un <motor modelos_relacionados="Modelo556">2.000cc 16v. de cuatro cilindros</motor> con <potencia>128</potencia> CV. Dispone de cambio manual ... el consumo medio de este monovolumen es <consumo_medio velocidad_km="100">11</consumo_medio> a los 100 km. El precio base es de 2.500.000.</modelo>
</concesionario>
