=== jlopez21178-tech/Llenguatje-de-marques/Tema 4/Teoria/Parte 3/extension.xsd
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:element name="persones">
    <xs:complexType>
      <xs:all>
        <xs:element name="persona" type="personaType" />
        <xs:element name="client" type="clientType" />
      </xs:all>
    </xs:complexType>
  </xs:element>

  <xs:complexType name="personaType">
    <xs:sequence>
      <xs:element name="nom" type="nomType" maxOccurs="unbounded" />
      <xs:element name="edat" type="xs:integer" minOccurs="0" />
      <xs:element name="data_naixement" type="xs:date" />
    </xs:sequence>
  </xs:complexType>

  <xs:complexType name="clientType">
    <xs:complexContent>
      <xs:extension base="personaType">
        <xs:sequence>
          <xs:element name="email" type="xs:string" />
        </xs:sequence>
      </xs:extension>
    </xs:complexContent>
  </xs:complexType>

  <xs:complexType name="nomType">
    <xs:simpleContent>
      <xs:extension base="xs:string">
        <xs:attribute name="lang" type="xs:string" />
      </xs:extension>
    </xs:simpleContent>
  </xs:complexType>

</xs:schema>

=== jlopez21178-tech/Llenguatje-de-marques/Tema 4/Teoria/Parte 3/extension.xml
<?xml version="1.0" encoding="UTF-8"?>

<persones
  xmlns:xs="http://www.w3.org/2001/XMLSchema-instance"
  xs:noNamespaceSchemaLocation="extension.xsd">
  <persona>
    <nom>Pepe</nom>
    <data_naixement>2025-10-31</data_naixement>
  </persona>

  <client>
    <nom lang="es">Pepe</nom>
    <edat>22</edat>
    <data_naixement>2025-10-31</data_naixement>
    <email>pepe@gmail.com</email>
  </client>
</persones>
